version: '3.3'
services:
  app1:
    build:
      dockerfile: Dockerfile
  web:
    image: "newimg"
    ports:
      - "8000:80"
    networks:
      - myNetwork
    depends_on:
      - db
      - myfile
  db:
    image: mysql
    env_file:
      - myconfig.env
  myfile:
    image: "newimg"
    # profiles:
    #   - mywebapp
  app:
    image: "redis:${tag}"
  
networks:
  myNetwork:
    driver: bridge 
  