# Use an official Python runtime as a parent image
FROM python:3.9-slim
# Set the working directory in the container
WORKDIR /app

# Copy the HTML, CSS, and JavaScript files into the container
COPY index.html .
COPY style.css .
COPY script.js .

VOLUME [ "/data" ]
# Expose port 8000 to allow outside access to your website
EXPOSE 8000

# Start a simple HTTP server using Python
CMD ["python", "-m", "http.server", "8000"]


